sample solution some bug

###Q3 Linux Shell Commands
##Q3.2
ls -l ~/mimic/hosp
ls -l ~/mimic/icu
The use of .csv.gz (compressed CSV) files instead of uncompressed .csv files is typically done to reduce file size. The ".gz" extension indicates that the file has been compressed using gzip compression, which is a widely used and efficient compression algorithm.
##Q3.3
zcat: Function: Zcat is used to concatenate and display compressed files. It is similar to the 'cat' command but is specifically designed to work with compressed files, particularly gzip-compressed files (with a ".gz" extension). Usage: zcat filename.gz 
zless: Function: Zless allows you to view the contents of compressed files page by page. It is similar to the 'less' command but works with gzip-compressed files, allowing you to scroll through the contents in a compressed state. Usage: zless filename.gz 
zmore: Function: Zmore is similar to Zless but is used to page through the contents of compressed files one screen at a time. It is an older command and is not as commonly used as Zless or other pager commands. Usage: zmore filename.gz 
zgrep: Function: Zgrep is used to search through compressed files for a specific pattern using regular expressions. It combines the functionality of 'grep' with the ability to work with gzip-compressed files. Usage: zgrep pattern filename.gz 
These commands are particularly useful when dealing with large compressed files, allowing users to view, search, and concatenate the contents without the need to manually decompress the files first.
##Q3.4
-rw-rw-r--@ 1 zhangruidong  staff  15516088 Jan  5  2023 /Users/zhangruidong/mimic/hosp/admissions.csv.gz
-rw-rw-r--@ 1 zhangruidong  staff  1939088924 Jan  5  2023 /Users/zhangruidong/mimic/hosp/labevents.csv.gz
-rw-rw-r--@ 1 zhangruidong  staff  2312631 Jan  5  2023 /Users/zhangruidong/mimic/hosp/patients.csv.gz
File: /Users/zhangruidong/mimic/hosp/admissions.csv.gz
  431232
File: /Users/zhangruidong/mimic/hosp/labevents.csv.gz
 118171368
File: /Users/zhangruidong/mimic/hosp/patients.csv.gz
  299713
##Q3.5
cd ~/mimic/hosp
# Display the first few lines of admissions.csv.gz
zcat < admissions.csv.gz | head
subject_id,hadm_id,admittime,dischtime,deathtime,admission_type,admit_provider_id,admission_location,discharge_location,insurance,language,marital_status,race,edregtime,edouttime,hospital_expire_flag
10000032,22595853,2180-05-06 22:23:00,2180-05-07 17:15:00,,URGENT,P874LG,TRANSFER FROM HOSPITAL,HOME,Other,ENGLISH,WIDOWED,WHITE,2180-05-06 19:17:00,2180-05-06 23:30:00,0
10000032,22841357,2180-06-26 18:27:00,2180-06-27 18:49:00,,EW EMER.,P09Q6Y,EMERGENCY ROOM,HOME,Medicaid,ENGLISH,WIDOWED,WHITE,2180-06-26 15:54:00,2180-06-26 21:31:00,0
10000032,25742920,2180-08-05 23:44:00,2180-08-07 17:50:00,,EW EMER.,P60CC5,EMERGENCY ROOM,HOSPICE,Medicaid,ENGLISH,WIDOWED,WHITE,2180-08-05 20:58:00,2180-08-06 01:44:00,0
10000032,29079034,2180-07-23 12:35:00,2180-07-25 17:55:00,,EW EMER.,P30KEH,EMERGENCY ROOM,HOME,Medicaid,ENGLISH,WIDOWED,WHITE,2180-07-23 05:54:00,2180-07-23 14:00:00,0
10000068,25022803,2160-03-03 23:16:00,2160-03-04 06:26:00,,EU OBSERVATION,P51VDL,EMERGENCY ROOM,,Other,ENGLISH,SINGLE,WHITE,2160-03-03 21:55:00,2160-03-04 06:26:00,0
10000084,23052089,2160-11-21 01:56:00,2160-11-25 14:52:00,,EW EMER.,P6957U,WALK-IN/SELF REFERRAL,HOME HEALTH CARE,Medicare,ENGLISH,MARRIED,WHITE,2160-11-20 20:36:00,2160-11-21 03:20:00,0
10000084,29888819,2160-12-28 05:11:00,2160-12-28 16:07:00,,EU OBSERVATION,P63AD6,PHYSICIAN REFERRAL,,Medicare,ENGLISH,MARRIED,WHITE,2160-12-27 18:32:00,2160-12-28 16:07:00,0
10000108,27250926,2163-09-27 23:17:00,2163-09-28 09:04:00,,EU OBSERVATION,P38XXV,EMERGENCY ROOM,,Other,ENGLISH,SINGLE,WHITE,2163-09-27 16:18:00,2163-09-28 09:04:00,0
10000117,22927623,2181-11-15 02:05:00,2181-11-15 14:52:00,,EU OBSERVATION,P2358X,EMERGENCY ROOM,,Other,ENGLISH,DIVORCED,WHITE,2181-11-14 21:51:00,2181-11-15 09:57:00,0

#rows in this data file: 431232
zcat < admissions.csv.gz | wc -l
# number of unique patients (identified by subject_id) are in admissions.csv.gz: 180733
# they are not match the number of patients listed in the patients.csv.gz file
zcat < admissions.csv.gz | awk -F',' 'NR>1 {print $1}' | sort -u | wc -l
zcat < admissions.csv.gz | tail -n +2 | cut -d',' -f1 | uniq | wc -l
# number of unique patients (identified by subject_id) are in patients.csv.gz: 299712
zcat < patients.csv.gz | tail -n +2 | cut -d',' -f1 | uniq | wc -l

##Q3.6
# admission_type
zcat < admissions.csv.gz | awk -F',' 'NR>1 {print $6}' | sort | uniq -c
# admission_location
zcat < admissions.csv.gz | awk -F',' 'NR>1 {print $8}' | sort | uniq -c
# insurance
zcat < admissions.csv.gz | awk -F',' 'NR>1 {print $10}' | sort | uniq -c
# ethnicity
zcat < admissions.csv.gz | awk -F',' 'NR>1 {print $13}' | sort | uniq -c

##Q3.7

zcat < labevents.csv.gz | wc -l
gzip -dk < labevents.csv.gz > ./labevents.csv
wc -l labevents.csv
# run time for labevents.csv.gz: real	0m19.109s user	0m22.936s sys	0m1.796s
time zcat < labevents.csv.gz | wc -l
# Measure time for labevents.csv: real	0m6.109s user	0m4.442s sys	0m1.403s
time wc -l labevents.csv
trade-off discussion for Storage vs. Speed: 
Compressed files offer significant storage savings but come at the cost of additional processing time during decompression when accessing the data. Access Speed: Uncompressed files are faster to access because there's no decompression step required. However, they consume more disk space.

##Q4.1
#1
wget -nc http://www.gutenberg.org/cache/epub/42671/pg42671.txt

for char in Elizabeth Jane Lydia Darcy
do
  echo "$char:"
  grep -o -i "$char" pg42671.txt | wc -l
done
Elizabeth:634
Jane:293
Lydia:171
Darcy:418
#Elizabeth was the most mentioned character in the book, I was right.
#The wget -nc command is used to download a file from a specified URL, and the -nc ensures that the file is not downloaded if it already exists locally. 
#2
echo 'hello, world' > test1.txt
echo 'hello, world' >> test2.txt
#The difference between the two commands is that the first command will overwrite the file if it already exists, while the second command will append the text to the end of the file if it already exists.
#3
chmod +x middle.sh
./middle.sh pg42671.txt 20 5
Editor: R. W. Chapman

Release date: May 9, 2013 [eBook #42671]

Language: English
#The output is a part of the content of the file pg42671.txt. The "$1", "$2", and "$3" in this shell script are used to represent the first, second, and third arguments passed to the script, respectively. In this case, the first argument is the file name, the second argument is the release date, and the third argument is the language.

##Q5
Try following commands in Bash and interpret the results: cal, cal 2024, cal 9 1752 (anything unusual?), date, hostname, arch, uname -a, uptime, who am i, who, w, id, last | head, echo {con,pre}{sent,fer}{s,ed}, time sleep 5, history | tail.

cal: displays a calendar for the current month
cal 2024: displays a calendar for the year 2024
cal 9 1752: displays a calendar for the month of September in the year 1752
date: displays the current date and time
hostname: displays the name of the current host
arch: displays the architecture of the current system
uname -a: displays detailed information about the current system
uptime: displays the current time, how long the system has been running, and the number of users currently logged in
who am i: displays the current user's login name
who: displays a list of all users currently logged in
w: displays a list of all users currently logged in, along with additional information such as the time they logged in and the current process they are running
id: displays the current user's UID and GID
last | head: displays a list of the last users to log in, along with the time they logged in and the terminal they used
echo {con,pre}{sent,fer}{s,ed}: displays the words "consents", "confered", "presents", and "preferred" on separate lines
time sleep 5: displays the amount of time it takes to run the "sleep 5" command
history | tail: displays the last 10 commands entered into the shell

##Q6
# the screenshot of Section 4.1.5 of the book is includeed in the hw1.Rmd file

